require("core.plugin_config.colorizer")
require("core.plugin_config.completions")
require("core.plugin_config.gitsigns")
require("core.plugin_config.indentBlankline")
require("core.plugin_config.lspconfig")
require("core.plugin_config.luasnip")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.undotree")
-- require("core.plugin_config.toggleterm")
